gha-runner-scale-set:
  # name of the runner scale set to create.  Defaults to the helm release name
  # runnerScaleSetName: ""

  ## githubConfigUrl is the GitHub url for where you want to configure runners
  ## ex: https://github.com/myorg/myrepo or https://github.com/myorg
  # githubConfigUrl: "https://github.com/sas-institute-rnd-pipeline-test"

  # name of kubernetes secret to use for authentication
  githubConfigSecret: controller-manager

  # template.spec will be modified if you change the container mode
  # with containerMode.type=dind, we will populate the template.spec with following pod spec
  template:
    spec:
      initContainers:
      - name: init-dind-externals
        image: ghcr.io/actions/actions-runner:latest
        command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
        volumeMounts:
          - name: dind-externals
            mountPath: /home/runner/tmpDir
      containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: DOCKER_HOST
            value: unix:///run/docker/docker.sock
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /run/docker
            readOnly: true
      - name: dind
        image: docker:dind
        args:
          - dockerd
          - --host=unix:///run/docker/docker.sock
          - --group=$(DOCKER_GROUP_GID)
        env:
          - name: DOCKER_GROUP_GID
            value: "123"
        securityContext:
          privileged: true
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /run/docker
          - name: dind-externals
            mountPath: /home/runner/externals
      volumes:
      - name: work
        emptyDir: {}
      - name: dind-sock
        emptyDir: {}
      - name: dind-externals
        emptyDir: {}


  ## Optional controller service account that needs to have required Role and RoleBinding
  ## to operate this gha-runner-scale-set installation.
  ## The helm chart will try to find the controller deployment and its service account at installation time.
  ## In case the helm chart can't find the right service account, you can explicitly pass in the following value
  ## to help it finish RoleBinding with the right service account.
  ## Note: if your controller is installed to only watch a single namespace, you have to pass these values explicitly.
  controllerServiceAccount:
    namespace: arc-system
    name: test-arc-gha-runner-scale-set-controller
